version: "3.9"

services:
  emulators:
    image: apata/firebase-tools:9.2.0-node12
    ports:
      - "9005:9005"
      - "9000:9000"
      - "8085:8085"
      - "8080:8080"
      - "5001:5001"
      - "5000:5000"
      - "4000:4000"
      - "3000:3000" # for webpack dev server
    volumes:
      - ./:/home/node
    command: tail -F anything
