version: "3.9"

services:
  emulators:
    build:
      context: ./firebase-tools
      args:
        - VERSION=9.2.1
    ports:
      - "9005:9005"
      - "9000:9000"
      - "8085:8085"
      - "8080:8080"
      - "5001:5001"
      - "5000:5000"
      - "4500:4500"
      - "4400:4400"
      - "4000:4000"
      - "3000:3000" # for webpack dev server
    volumes:
      - ./:/home/node/app
    command: tail -F anything
